(copy_files ../*.*)
(alias (name runtest)
  (deps (alias runtest_config)))
; TEST FILE "model_var_in_return.c"
(alias (name "model_var_in_return.wtests")
  (deps (alias "model_var_in_return.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "model_var_in_return.c")
  (deps (alias "model_var_in_return.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/model_var_in_return.c
  (alias "model_var_in_return.0.exec.wtests")
  (targets "model_var_in_return.0.err.log" "model_var_in_return.0.res.log"  "model_var_in_return.out.c" "saida_harness_model_var_in_return.c" )
  (deps "model_var_in_return.0.exec.wtests" "../oracle/model_var_in_return.0.res.oracle" "../oracle/model_var_in_return.0.err.oracle"  "../oracle/model_var_in_return.out.c" "../oracle/saida_harness_model_var_in_return.c" "model_var_in_return.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "model_var_in_return.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_return.out.c > \"model_var_in_return.0.res.log\" 2> \"model_var_in_return.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "model_var_in_return.c"
  (alias model_var_in_return.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_return.out.c" "model_var_in_return.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "model_var_in_return.c"
  (alias model_var_in_return.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_model_var_in_return.c" "saida_harness_model_var_in_return.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "model_var_in_return.c"
  (alias "model_var_in_return.0.exec")
  (deps  "model_var_in_return.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_return.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "model_var_in_return.c"
  (alias "model_var_in_return.0.exec.show")
  (deps  "model_var_in_return.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_return.out.c > \"model_var_in_return.0.res.log\" 2> \"model_var_in_return.0.err.log\"'"))
)
(rule
  (alias "model_var_in_return.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_return.0.res.oracle" "model_var_in_return.0.res.log"))
)
(rule
  (alias "model_var_in_return.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_return.0.err.oracle" "model_var_in_return.0.err.log"))
)
(alias (name "model_var_in_return.diff")
  (deps (alias "model_var_in_return.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "model_var_in_return.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "model_var_in_struct.c"
(alias (name "model_var_in_struct.wtests")
  (deps (alias "model_var_in_struct.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "model_var_in_struct.c")
  (deps (alias "model_var_in_struct.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/model_var_in_struct.c
  (alias "model_var_in_struct.0.exec.wtests")
  (targets "model_var_in_struct.0.err.log" "model_var_in_struct.0.res.log"  "model_var_in_struct.out.c" "saida_harness_model_var_in_struct.c" )
  (deps "model_var_in_struct.0.exec.wtests" "../oracle/model_var_in_struct.0.res.oracle" "../oracle/model_var_in_struct.0.err.oracle"  "../oracle/model_var_in_struct.out.c" "../oracle/saida_harness_model_var_in_struct.c" "model_var_in_struct.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "model_var_in_struct.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_struct.out.c > \"model_var_in_struct.0.res.log\" 2> \"model_var_in_struct.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "model_var_in_struct.c"
  (alias model_var_in_struct.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_struct.out.c" "model_var_in_struct.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "model_var_in_struct.c"
  (alias model_var_in_struct.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_model_var_in_struct.c" "saida_harness_model_var_in_struct.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "model_var_in_struct.c"
  (alias "model_var_in_struct.0.exec")
  (deps  "model_var_in_struct.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_struct.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "model_var_in_struct.c"
  (alias "model_var_in_struct.0.exec.show")
  (deps  "model_var_in_struct.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_struct.out.c > \"model_var_in_struct.0.res.log\" 2> \"model_var_in_struct.0.err.log\"'"))
)
(rule
  (alias "model_var_in_struct.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_struct.0.res.oracle" "model_var_in_struct.0.res.log"))
)
(rule
  (alias "model_var_in_struct.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_struct.0.err.oracle" "model_var_in_struct.0.err.log"))
)
(alias (name "model_var_in_struct.diff")
  (deps (alias "model_var_in_struct.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "model_var_in_struct.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "model_var_in_nested_return.c"
(alias (name "model_var_in_nested_return.wtests")
  (deps (alias "model_var_in_nested_return.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "model_var_in_nested_return.c")
  (deps (alias "model_var_in_nested_return.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/model_var_in_nested_return.c
  (alias "model_var_in_nested_return.0.exec.wtests")
  (targets "model_var_in_nested_return.0.err.log" "model_var_in_nested_return.0.res.log"  "model_var_in_nested_return.out.c" "saida_harness_model_var_in_nested_return.c" )
  (deps "model_var_in_nested_return.0.exec.wtests" "../oracle/model_var_in_nested_return.0.res.oracle" "../oracle/model_var_in_nested_return.0.err.oracle"  "../oracle/model_var_in_nested_return.out.c" "../oracle/saida_harness_model_var_in_nested_return.c" "model_var_in_nested_return.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "model_var_in_nested_return.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_return.out.c > \"model_var_in_nested_return.0.res.log\" 2> \"model_var_in_nested_return.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "model_var_in_nested_return.c"
  (alias model_var_in_nested_return.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_return.out.c" "model_var_in_nested_return.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "model_var_in_nested_return.c"
  (alias model_var_in_nested_return.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_model_var_in_nested_return.c" "saida_harness_model_var_in_nested_return.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "model_var_in_nested_return.c"
  (alias "model_var_in_nested_return.0.exec")
  (deps  "model_var_in_nested_return.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_return.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "model_var_in_nested_return.c"
  (alias "model_var_in_nested_return.0.exec.show")
  (deps  "model_var_in_nested_return.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_return.c -lib-entry -main=\"start\" -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_return.out.c > \"model_var_in_nested_return.0.res.log\" 2> \"model_var_in_nested_return.0.err.log\"'"))
)
(rule
  (alias "model_var_in_nested_return.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_return.0.res.oracle" "model_var_in_nested_return.0.res.log"))
)
(rule
  (alias "model_var_in_nested_return.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_return.0.err.oracle" "model_var_in_nested_return.0.err.log"))
)
(alias (name "model_var_in_nested_return.diff")
  (deps (alias "model_var_in_nested_return.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "model_var_in_nested_return.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "nested_structs.c"
(alias (name "nested_structs.wtests")
  (deps (alias "nested_structs.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "nested_structs.c")
  (deps (alias "nested_structs.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/nested_structs.c
  (alias "nested_structs.0.exec.wtests")
  (targets "nested_structs.0.err.log" "nested_structs.0.res.log"  "nested_structs.out.c" "saida_harness_nested_structs.c" )
  (deps "nested_structs.0.exec.wtests" "../oracle/nested_structs.0.res.oracle" "../oracle/nested_structs.0.err.oracle"  "../oracle/nested_structs.out.c" "../oracle/saida_harness_nested_structs.c" "nested_structs.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "nested_structs.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl -solutionReconstruction:wp\" -saida-keep-tmp -saida-out=nested_structs.out.c > \"nested_structs.0.res.log\" 2> \"nested_structs.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "nested_structs.c"
  (alias nested_structs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_structs.out.c" "nested_structs.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "nested_structs.c"
  (alias nested_structs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_nested_structs.c" "saida_harness_nested_structs.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "nested_structs.c"
  (alias "nested_structs.0.exec")
  (deps  "nested_structs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl -solutionReconstruction:wp\" -saida-keep-tmp -saida-out=nested_structs.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "nested_structs.c"
  (alias "nested_structs.0.exec.show")
  (deps  "nested_structs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl -solutionReconstruction:wp\" -saida-keep-tmp -saida-out=nested_structs.out.c > \"nested_structs.0.res.log\" 2> \"nested_structs.0.err.log\"'"))
)
(rule
  (alias "nested_structs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_structs.0.res.oracle" "nested_structs.0.res.log"))
)
(rule
  (alias "nested_structs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_structs.0.err.oracle" "nested_structs.0.err.log"))
)
(alias (name "nested_structs.diff")
  (deps (alias "nested_structs.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "nested_structs.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "mixed_member_ptr.c"
(alias (name "mixed_member_ptr.wtests")
  (deps (alias "mixed_member_ptr.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "mixed_member_ptr.c")
  (deps (alias "mixed_member_ptr.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/mixed_member_ptr.c
  (alias "mixed_member_ptr.0.exec.wtests")
  (targets "mixed_member_ptr.0.err.log" "mixed_member_ptr.0.res.log"  "mixed_member_ptr.out.c" "saida_harness_mixed_member_ptr.c" )
  (deps "mixed_member_ptr.0.exec.wtests" "../oracle/mixed_member_ptr.0.res.oracle" "../oracle/mixed_member_ptr.0.err.oracle"  "../oracle/mixed_member_ptr.out.c" "../oracle/saida_harness_mixed_member_ptr.c" "mixed_member_ptr.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "mixed_member_ptr.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    mixed_member_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=mixed_member_ptr.out.c > \"mixed_member_ptr.0.res.log\" 2> \"mixed_member_ptr.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "mixed_member_ptr.c"
  (alias mixed_member_ptr.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/mixed_member_ptr.out.c" "mixed_member_ptr.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "mixed_member_ptr.c"
  (alias mixed_member_ptr.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_mixed_member_ptr.c" "saida_harness_mixed_member_ptr.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "mixed_member_ptr.c"
  (alias "mixed_member_ptr.0.exec")
  (deps  "mixed_member_ptr.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    mixed_member_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=mixed_member_ptr.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "mixed_member_ptr.c"
  (alias "mixed_member_ptr.0.exec.show")
  (deps  "mixed_member_ptr.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    mixed_member_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=mixed_member_ptr.out.c > \"mixed_member_ptr.0.res.log\" 2> \"mixed_member_ptr.0.err.log\"'"))
)
(rule
  (alias "mixed_member_ptr.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/mixed_member_ptr.0.res.oracle" "mixed_member_ptr.0.res.log"))
)
(rule
  (alias "mixed_member_ptr.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/mixed_member_ptr.0.err.oracle" "mixed_member_ptr.0.err.log"))
)
(alias (name "mixed_member_ptr.diff")
  (deps (alias "mixed_member_ptr.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "mixed_member_ptr.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "nested_struct_ptrs.c"
(alias (name "nested_struct_ptrs.wtests")
  (deps (alias "nested_struct_ptrs.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "nested_struct_ptrs.c")
  (deps (alias "nested_struct_ptrs.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/nested_struct_ptrs.c
  (alias "nested_struct_ptrs.0.exec.wtests")
  (targets "nested_struct_ptrs.0.err.log" "nested_struct_ptrs.0.res.log"  "nested_struct_ptrs.out.c" "saida_harness_nested_struct_ptrs.c" )
  (deps "nested_struct_ptrs.0.exec.wtests" "../oracle/nested_struct_ptrs.0.res.oracle" "../oracle/nested_struct_ptrs.0.err.oracle"  "../oracle/nested_struct_ptrs.out.c" "../oracle/saida_harness_nested_struct_ptrs.c" "nested_struct_ptrs.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "nested_struct_ptrs.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    nested_struct_ptrs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nested_struct_ptrs.out.c > \"nested_struct_ptrs.0.res.log\" 2> \"nested_struct_ptrs.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "nested_struct_ptrs.c"
  (alias nested_struct_ptrs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_struct_ptrs.out.c" "nested_struct_ptrs.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "nested_struct_ptrs.c"
  (alias nested_struct_ptrs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_nested_struct_ptrs.c" "saida_harness_nested_struct_ptrs.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "nested_struct_ptrs.c"
  (alias "nested_struct_ptrs.0.exec")
  (deps  "nested_struct_ptrs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    nested_struct_ptrs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nested_struct_ptrs.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "nested_struct_ptrs.c"
  (alias "nested_struct_ptrs.0.exec.show")
  (deps  "nested_struct_ptrs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    nested_struct_ptrs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nested_struct_ptrs.out.c > \"nested_struct_ptrs.0.res.log\" 2> \"nested_struct_ptrs.0.err.log\"'"))
)
(rule
  (alias "nested_struct_ptrs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_struct_ptrs.0.res.oracle" "nested_struct_ptrs.0.res.log"))
)
(rule
  (alias "nested_struct_ptrs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nested_struct_ptrs.0.err.oracle" "nested_struct_ptrs.0.err.log"))
)
(alias (name "nested_struct_ptrs.diff")
  (deps (alias "nested_struct_ptrs.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "nested_struct_ptrs.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "model_var_in_nested_structs.c"
(alias (name "model_var_in_nested_structs.wtests")
  (deps (alias "model_var_in_nested_structs.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "model_var_in_nested_structs.c")
  (deps (alias "model_var_in_nested_structs.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/structs/model_var_in_nested_structs.c
  (alias "model_var_in_nested_structs.0.exec.wtests")
  (targets "model_var_in_nested_structs.0.err.log" "model_var_in_nested_structs.0.res.log"  "model_var_in_nested_structs.out.c" "saida_harness_model_var_in_nested_structs.c" )
  (deps "model_var_in_nested_structs.0.exec.wtests" "../oracle/model_var_in_nested_structs.0.res.oracle" "../oracle/model_var_in_nested_structs.0.err.oracle"  "../oracle/model_var_in_nested_structs.out.c" "../oracle/saida_harness_model_var_in_nested_structs.c" "model_var_in_nested_structs.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "model_var_in_nested_structs.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_structs.out.c > \"model_var_in_nested_structs.0.res.log\" 2> \"model_var_in_nested_structs.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "model_var_in_nested_structs.c"
  (alias model_var_in_nested_structs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_structs.out.c" "model_var_in_nested_structs.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "model_var_in_nested_structs.c"
  (alias model_var_in_nested_structs.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_model_var_in_nested_structs.c" "saida_harness_model_var_in_nested_structs.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "model_var_in_nested_structs.c"
  (alias "model_var_in_nested_structs.0.exec")
  (deps  "model_var_in_nested_structs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_structs.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "model_var_in_nested_structs.c"
  (alias "model_var_in_nested_structs.0.exec.show")
  (deps  "model_var_in_nested_structs.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    model_var_in_nested_structs.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=model_var_in_nested_structs.out.c > \"model_var_in_nested_structs.0.res.log\" 2> \"model_var_in_nested_structs.0.err.log\"'"))
)
(rule
  (alias "model_var_in_nested_structs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_structs.0.res.oracle" "model_var_in_nested_structs.0.res.log"))
)
(rule
  (alias "model_var_in_nested_structs.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/model_var_in_nested_structs.0.err.oracle" "model_var_in_nested_structs.0.err.log"))
)
(alias (name "model_var_in_nested_structs.diff")
  (deps (alias "model_var_in_nested_structs.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "model_var_in_nested_structs.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name disabled_runtest)
  (deps (alias disabled_runtest_config)))
(alias (name runtest)
  (deps (alias disabled_runtest)))
(alias (name runtest_config)
  (deps (alias disabled_runtest_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_runtest_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-saida.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/structs/runtest_config\n")
                 (echo "- \%{lib-available:frama-c-saida.core}: " %{lib-available:frama-c-saida.core} "\n")
  ))
)
