(copy_files ../*.*)
(alias (name runtest)
  (deps (alias runtest_config)))
; TEST FILE "sum.c"
(alias (name "sum.wtests")
  (deps (alias "sum.0.exec.wtests") (alias sum.0.execnow.wtests))) ; to perform all sub-tests related to a file
(alias (name "sum.c")
  (deps (alias "sum.0.exec") (alias sum.0.execnow.wtests))) ; to reproduce and visualize all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/sum.c
  (alias "sum.0.exec.wtests")
  (targets "sum.0.err.log" "sum.0.res.log" "sum.out.c")
  (deps "sum.0.exec.wtests" "../oracle/sum.0.res.oracle" "../oracle/sum.0.err.oracle" "sum.c" (package frama-c) (package "frama-c-saida"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (run frama-c-wtests -brief "sum.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida sum.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=sum.out.c > \"sum.0.res.log\" 2> \"sum.0.err.log\""))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "sum.c"
  (alias "sum.0.exec")
  (deps "sum.c" (package frama-c) (package "frama-c-saida") (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida sum.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=sum.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "sum.c"
  (alias "sum.0.exec.show")
  (deps "sum.c" (package frama-c) (package "frama-c-saida") (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida sum.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=sum.out.c > \"sum.0.res.log\" 2> \"sum.0.err.log\"'"))
)
(rule
  (alias sum.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (diff "../oracle/sum.0.res.oracle" "sum.0.res.log"))
)
(rule
  (alias sum.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (diff "../oracle/sum.0.err.oracle" "sum.0.err.log"))
)
(alias (name "sum.diff")
  (deps (alias "sum.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name runtest_config)
  (deps (alias "sum.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(rule ; EXECNOW #0 OF TEST FILE tests/basic/sum.c
  (alias sum.0.execnow.wtests)
  (deps "../oracle/sum.parse.log" "sum.c" "sum.out.c" (package frama-c) (package "frama-c-saida"))
  (targets "sum.parse.log")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (run frama-c-wtests -brief %{dep:sum.0.execnow.wtests} "grep -q \"contract for sum\" sum.out.c && frama-c -check -no-autoload-plugins sum.out.c > sum.parse.log"))
)
(rule ; SHOW EXECNOW COMMAND #0 OF TEST FILE "sum.c"
  (alias sum.0.execnow.show)
  (deps "sum.c" "sum.out.c" (package frama-c) (package "frama-c-saida") (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (system "echo 'grep -q \"contract for sum\" sum.out.c && frama-c -check -no-autoload-plugins sum.out.c > sum.parse.log'"))
)
(rule ; COMPARE TARGET #0 OF EXECNOW #0 FOR TEST FILE "sum.c"
  (alias sum.0.execnow.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
  (action (diff "../oracle/sum.parse.log" "sum.parse.log"))
)
(alias (name "sum.diff")
  (deps (alias "sum.0.execnow.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name runtest_config)
  (deps (alias "sum.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "char_const.c"
(alias (name "char_const.wtests")
  (deps (alias "char_const.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "char_const.c")
  (deps (alias "char_const.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/char_const.c
  (alias "char_const.0.exec.wtests")
  (targets "char_const.0.err.log" "char_const.0.res.log"  "char_const.out.c" "saida_harness_char_const.c" )
  (deps "char_const.0.exec.wtests" "../oracle/char_const.0.res.oracle" "../oracle/char_const.0.err.oracle"  "../oracle/char_const.out.c" "../oracle/saida_harness_char_const.c" "char_const.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "char_const.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    char_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=char_const.out.c > \"char_const.0.res.log\" 2> \"char_const.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "char_const.c"
  (alias char_const.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/char_const.out.c" "char_const.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "char_const.c"
  (alias char_const.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_char_const.c" "saida_harness_char_const.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "char_const.c"
  (alias "char_const.0.exec")
  (deps  "char_const.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    char_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=char_const.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "char_const.c"
  (alias "char_const.0.exec.show")
  (deps  "char_const.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    char_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=char_const.out.c > \"char_const.0.res.log\" 2> \"char_const.0.err.log\"'"))
)
(rule
  (alias "char_const.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/char_const.0.res.oracle" "char_const.0.res.log"))
)
(rule
  (alias "char_const.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/char_const.0.err.oracle" "char_const.0.err.log"))
)
(alias (name "char_const.diff")
  (deps (alias "char_const.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "char_const.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "behavior.c"
(alias (name "behavior.wtests")
  (deps (alias "behavior.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "behavior.c")
  (deps (alias "behavior.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/behavior.c
  (alias "behavior.0.exec.wtests")
  (targets "behavior.0.err.log" "behavior.0.res.log"  "behavior.out.c" "saida_harness_behavior.c" )
  (deps "behavior.0.exec.wtests" "../oracle/behavior.0.res.oracle" "../oracle/behavior.0.err.oracle"  "../oracle/behavior.out.c" "../oracle/saida_harness_behavior.c" "behavior.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "behavior.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    behavior.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=behavior.out.c > \"behavior.0.res.log\" 2> \"behavior.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "behavior.c"
  (alias behavior.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/behavior.out.c" "behavior.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "behavior.c"
  (alias behavior.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_behavior.c" "saida_harness_behavior.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "behavior.c"
  (alias "behavior.0.exec")
  (deps  "behavior.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    behavior.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=behavior.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "behavior.c"
  (alias "behavior.0.exec.show")
  (deps  "behavior.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    behavior.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=behavior.out.c > \"behavior.0.res.log\" 2> \"behavior.0.err.log\"'"))
)
(rule
  (alias "behavior.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/behavior.0.res.oracle" "behavior.0.res.log"))
)
(rule
  (alias "behavior.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/behavior.0.err.oracle" "behavior.0.err.log"))
)
(alias (name "behavior.diff")
  (deps (alias "behavior.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "behavior.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "ternary_term.c"
(alias (name "ternary_term.wtests")
  (deps (alias "ternary_term.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "ternary_term.c")
  (deps (alias "ternary_term.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/ternary_term.c
  (alias "ternary_term.0.exec.wtests")
  (targets "ternary_term.0.err.log" "ternary_term.0.res.log"  "ternary_term.out.c" "saida_harness_ternary_term.c" )
  (deps "ternary_term.0.exec.wtests" "../oracle/ternary_term.0.res.oracle" "../oracle/ternary_term.0.err.oracle"  "../oracle/ternary_term.out.c" "../oracle/saida_harness_ternary_term.c" "ternary_term.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "ternary_term.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_term.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_term.out.c > \"ternary_term.0.res.log\" 2> \"ternary_term.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "ternary_term.c"
  (alias ternary_term.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_term.out.c" "ternary_term.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "ternary_term.c"
  (alias ternary_term.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_ternary_term.c" "saida_harness_ternary_term.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "ternary_term.c"
  (alias "ternary_term.0.exec")
  (deps  "ternary_term.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_term.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_term.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "ternary_term.c"
  (alias "ternary_term.0.exec.show")
  (deps  "ternary_term.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_term.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_term.out.c > \"ternary_term.0.res.log\" 2> \"ternary_term.0.err.log\"'"))
)
(rule
  (alias "ternary_term.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_term.0.res.oracle" "ternary_term.0.res.log"))
)
(rule
  (alias "ternary_term.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_term.0.err.oracle" "ternary_term.0.err.log"))
)
(alias (name "ternary_term.diff")
  (deps (alias "ternary_term.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "ternary_term.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "simple_ptr.c"
(alias (name "simple_ptr.wtests")
  (deps (alias "simple_ptr.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "simple_ptr.c")
  (deps (alias "simple_ptr.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/simple_ptr.c
  (alias "simple_ptr.0.exec.wtests")
  (targets "simple_ptr.0.err.log" "simple_ptr.0.res.log"  "simple_ptr.out.c" )
  (deps "simple_ptr.0.exec.wtests" "../oracle/simple_ptr.0.res.oracle" "../oracle/simple_ptr.0.err.oracle"  "../oracle/simple_ptr.out.c" "simple_ptr.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "simple_ptr.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    simple_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple_ptr.out.c > \"simple_ptr.0.res.log\" 2> \"simple_ptr.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "simple_ptr.c"
  (alias simple_ptr.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple_ptr.out.c" "simple_ptr.out.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "simple_ptr.c"
  (alias "simple_ptr.0.exec")
  (deps  "simple_ptr.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    simple_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple_ptr.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "simple_ptr.c"
  (alias "simple_ptr.0.exec.show")
  (deps  "simple_ptr.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    simple_ptr.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple_ptr.out.c > \"simple_ptr.0.res.log\" 2> \"simple_ptr.0.err.log\"'"))
)
(rule
  (alias "simple_ptr.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple_ptr.0.res.oracle" "simple_ptr.0.res.log"))
)
(rule
  (alias "simple_ptr.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple_ptr.0.err.oracle" "simple_ptr.0.err.log"))
)
(alias (name "simple_ptr.diff")
  (deps (alias "simple_ptr.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "simple_ptr.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "simple.c"
(alias (name "simple.wtests")
  (deps (alias "simple.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "simple.c")
  (deps (alias "simple.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/simple.c
  (alias "simple.0.exec.wtests")
  (targets "simple.0.err.log" "simple.0.res.log"  "simple.out.c" )
  (deps "simple.0.exec.wtests" "../oracle/simple.0.res.oracle" "../oracle/simple.0.err.oracle"  "../oracle/simple.out.c" "simple.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "simple.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    simple.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple.out.c > \"simple.0.res.log\" 2> \"simple.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "simple.c"
  (alias simple.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple.out.c" "simple.out.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "simple.c"
  (alias "simple.0.exec")
  (deps  "simple.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    simple.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "simple.c"
  (alias "simple.0.exec.show")
  (deps  "simple.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    simple.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-out=simple.out.c > \"simple.0.res.log\" 2> \"simple.0.err.log\"'"))
)
(rule
  (alias "simple.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple.0.res.oracle" "simple.0.res.log"))
)
(rule
  (alias "simple.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/simple.0.err.oracle" "simple.0.err.log"))
)
(alias (name "simple.diff")
  (deps (alias "simple.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "simple.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "multiple_contracts.c"
(alias (name "multiple_contracts.wtests")
  (deps (alias "multiple_contracts.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "multiple_contracts.c")
  (deps (alias "multiple_contracts.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/multiple_contracts.c
  (alias "multiple_contracts.0.exec.wtests")
  (targets "multiple_contracts.0.err.log" "multiple_contracts.0.res.log"  "multiple_contracts.out.c" "saida_harness_multiple_contracts.c" )
  (deps "multiple_contracts.0.exec.wtests" "../oracle/multiple_contracts.0.res.oracle" "../oracle/multiple_contracts.0.err.oracle"  "../oracle/multiple_contracts.out.c" "../oracle/saida_harness_multiple_contracts.c" "multiple_contracts.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "multiple_contracts.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    multiple_contracts.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=multiple_contracts.out.c > \"multiple_contracts.0.res.log\" 2> \"multiple_contracts.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "multiple_contracts.c"
  (alias multiple_contracts.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/multiple_contracts.out.c" "multiple_contracts.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "multiple_contracts.c"
  (alias multiple_contracts.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_multiple_contracts.c" "saida_harness_multiple_contracts.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "multiple_contracts.c"
  (alias "multiple_contracts.0.exec")
  (deps  "multiple_contracts.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    multiple_contracts.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=multiple_contracts.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "multiple_contracts.c"
  (alias "multiple_contracts.0.exec.show")
  (deps  "multiple_contracts.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    multiple_contracts.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=multiple_contracts.out.c > \"multiple_contracts.0.res.log\" 2> \"multiple_contracts.0.err.log\"'"))
)
(rule
  (alias "multiple_contracts.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/multiple_contracts.0.res.oracle" "multiple_contracts.0.res.log"))
)
(rule
  (alias "multiple_contracts.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/multiple_contracts.0.err.oracle" "multiple_contracts.0.err.log"))
)
(alias (name "multiple_contracts.diff")
  (deps (alias "multiple_contracts.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "multiple_contracts.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "ternary_predicate.c"
(alias (name "ternary_predicate.wtests")
  (deps (alias "ternary_predicate.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "ternary_predicate.c")
  (deps (alias "ternary_predicate.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/ternary_predicate.c
  (alias "ternary_predicate.0.exec.wtests")
  (targets "ternary_predicate.0.err.log" "ternary_predicate.0.res.log"  "ternary_predicate.out.c" "saida_harness_ternary_predicate.c" )
  (deps "ternary_predicate.0.exec.wtests" "../oracle/ternary_predicate.0.res.oracle" "../oracle/ternary_predicate.0.err.oracle"  "../oracle/ternary_predicate.out.c" "../oracle/saida_harness_ternary_predicate.c" "ternary_predicate.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "ternary_predicate.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_predicate.out.c > \"ternary_predicate.0.res.log\" 2> \"ternary_predicate.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "ternary_predicate.c"
  (alias ternary_predicate.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_predicate.out.c" "ternary_predicate.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "ternary_predicate.c"
  (alias ternary_predicate.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_ternary_predicate.c" "saida_harness_ternary_predicate.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "ternary_predicate.c"
  (alias "ternary_predicate.0.exec")
  (deps  "ternary_predicate.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_predicate.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "ternary_predicate.c"
  (alias "ternary_predicate.0.exec.show")
  (deps  "ternary_predicate.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    ternary_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=ternary_predicate.out.c > \"ternary_predicate.0.res.log\" 2> \"ternary_predicate.0.err.log\"'"))
)
(rule
  (alias "ternary_predicate.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_predicate.0.res.oracle" "ternary_predicate.0.res.log"))
)
(rule
  (alias "ternary_predicate.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/ternary_predicate.0.err.oracle" "ternary_predicate.0.err.log"))
)
(alias (name "ternary_predicate.diff")
  (deps (alias "ternary_predicate.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "ternary_predicate.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "implies.c"
(alias (name "implies.wtests")
  (deps (alias "implies.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "implies.c")
  (deps (alias "implies.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/implies.c
  (alias "implies.0.exec.wtests")
  (targets "implies.0.err.log" "implies.0.res.log"  "implies.out.c" "saida_harness_implies.c" )
  (deps "implies.0.exec.wtests" "../oracle/implies.0.res.oracle" "../oracle/implies.0.err.oracle"  "../oracle/implies.out.c" "../oracle/saida_harness_implies.c" "implies.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "implies.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    implies.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=implies.out.c > \"implies.0.res.log\" 2> \"implies.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "implies.c"
  (alias implies.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/implies.out.c" "implies.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "implies.c"
  (alias implies.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_implies.c" "saida_harness_implies.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "implies.c"
  (alias "implies.0.exec")
  (deps  "implies.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    implies.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=implies.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "implies.c"
  (alias "implies.0.exec.show")
  (deps  "implies.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    implies.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=implies.out.c > \"implies.0.res.log\" 2> \"implies.0.err.log\"'"))
)
(rule
  (alias "implies.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/implies.0.res.oracle" "implies.0.res.log"))
)
(rule
  (alias "implies.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/implies.0.err.oracle" "implies.0.err.log"))
)
(alias (name "implies.diff")
  (deps (alias "implies.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "implies.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "func_arguments.c"
(alias (name "func_arguments.wtests")
  (deps (alias "func_arguments.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "func_arguments.c")
  (deps (alias "func_arguments.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/func_arguments.c
  (alias "func_arguments.0.exec.wtests")
  (targets "func_arguments.0.err.log" "func_arguments.0.res.log"  "func_arguments.out.c" "saida_harness_func_arguments.c" )
  (deps "func_arguments.0.exec.wtests" "../oracle/func_arguments.0.res.oracle" "../oracle/func_arguments.0.err.oracle"  "../oracle/func_arguments.out.c" "../oracle/saida_harness_func_arguments.c" "func_arguments.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "func_arguments.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    func_arguments.c -lib-entry -main=start -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=func_arguments.out.c > \"func_arguments.0.res.log\" 2> \"func_arguments.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "func_arguments.c"
  (alias func_arguments.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/func_arguments.out.c" "func_arguments.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "func_arguments.c"
  (alias func_arguments.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_func_arguments.c" "saida_harness_func_arguments.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "func_arguments.c"
  (alias "func_arguments.0.exec")
  (deps  "func_arguments.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    func_arguments.c -lib-entry -main=start -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=func_arguments.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "func_arguments.c"
  (alias "func_arguments.0.exec.show")
  (deps  "func_arguments.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    func_arguments.c -lib-entry -main=start -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=func_arguments.out.c > \"func_arguments.0.res.log\" 2> \"func_arguments.0.err.log\"'"))
)
(rule
  (alias "func_arguments.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/func_arguments.0.res.oracle" "func_arguments.0.res.log"))
)
(rule
  (alias "func_arguments.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/func_arguments.0.err.oracle" "func_arguments.0.err.log"))
)
(alias (name "func_arguments.diff")
  (deps (alias "func_arguments.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "func_arguments.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "let2.c"
(alias (name "let2.wtests")
  (deps (alias "let2.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "let2.c")
  (deps (alias "let2.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/let2.c
  (alias "let2.0.exec.wtests")
  (targets "let2.0.err.log" "let2.0.res.log"  "saida_harness_let2.c" )
  (deps "let2.0.exec.wtests" "../oracle/let2.0.res.oracle" "../oracle/let2.0.err.oracle"  "../oracle/saida_harness_let2.c" "let2.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "let2.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    let2.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let2.out.c > \"let2.0.res.log\" 2> \"let2.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "let2.c"
  (alias let2.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_let2.c" "saida_harness_let2.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "let2.c"
  (alias "let2.0.exec")
  (deps  "let2.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    let2.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let2.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "let2.c"
  (alias "let2.0.exec.show")
  (deps  "let2.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    let2.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let2.out.c > \"let2.0.res.log\" 2> \"let2.0.err.log\"'"))
)
(rule
  (alias "let2.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/let2.0.res.oracle" "let2.0.res.log"))
)
(rule
  (alias "let2.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/let2.0.err.oracle" "let2.0.err.log"))
)
(alias (name "let2.diff")
  (deps (alias "let2.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "let2.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "let.c"
(alias (name "let.wtests")
  (deps (alias "let.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "let.c")
  (deps (alias "let.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/let.c
  (alias "let.0.exec.wtests")
  (targets "let.0.err.log" "let.0.res.log"  "saida_harness_let.c" )
  (deps "let.0.exec.wtests" "../oracle/let.0.res.oracle" "../oracle/let.0.err.oracle"  "../oracle/saida_harness_let.c" "let.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "let.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    let.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let.out.c > \"let.0.res.log\" 2> \"let.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "let.c"
  (alias let.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_let.c" "saida_harness_let.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "let.c"
  (alias "let.0.exec")
  (deps  "let.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    let.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "let.c"
  (alias "let.0.exec.show")
  (deps  "let.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    let.c -lib-entry -main=f -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=let.out.c > \"let.0.res.log\" 2> \"let.0.err.log\"'"))
)
(rule
  (alias "let.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/let.0.res.oracle" "let.0.res.log"))
)
(rule
  (alias "let.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/let.0.err.oracle" "let.0.err.log"))
)
(alias (name "let.diff")
  (deps (alias "let.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "let.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "bool_const.c"
(alias (name "bool_const.wtests")
  (deps (alias "bool_const.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "bool_const.c")
  (deps (alias "bool_const.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/bool_const.c
  (alias "bool_const.0.exec.wtests")
  (targets "bool_const.0.err.log" "bool_const.0.res.log"  "bool_const.out.c" "saida_harness_bool_const.c" )
  (deps "bool_const.0.exec.wtests" "../oracle/bool_const.0.res.oracle" "../oracle/bool_const.0.err.oracle"  "../oracle/bool_const.out.c" "../oracle/saida_harness_bool_const.c" "bool_const.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "bool_const.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    bool_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=bool_const.out.c > \"bool_const.0.res.log\" 2> \"bool_const.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "bool_const.c"
  (alias bool_const.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/bool_const.out.c" "bool_const.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "bool_const.c"
  (alias bool_const.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_bool_const.c" "saida_harness_bool_const.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "bool_const.c"
  (alias "bool_const.0.exec")
  (deps  "bool_const.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    bool_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=bool_const.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "bool_const.c"
  (alias "bool_const.0.exec.show")
  (deps  "bool_const.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    bool_const.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=bool_const.out.c > \"bool_const.0.res.log\" 2> \"bool_const.0.err.log\"'"))
)
(rule
  (alias "bool_const.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/bool_const.0.res.oracle" "bool_const.0.res.log"))
)
(rule
  (alias "bool_const.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/bool_const.0.err.oracle" "bool_const.0.err.log"))
)
(alias (name "bool_const.diff")
  (deps (alias "bool_const.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "bool_const.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "old_predicate.c"
(alias (name "old_predicate.wtests")
  (deps (alias "old_predicate.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "old_predicate.c")
  (deps (alias "old_predicate.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/old_predicate.c
  (alias "old_predicate.0.exec.wtests")
  (targets "old_predicate.0.err.log" "old_predicate.0.res.log"  "old_predicate.out.c" "saida_harness_old_predicate.c" )
  (deps "old_predicate.0.exec.wtests" "../oracle/old_predicate.0.res.oracle" "../oracle/old_predicate.0.err.oracle"  "../oracle/old_predicate.out.c" "../oracle/saida_harness_old_predicate.c" "old_predicate.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "old_predicate.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    old_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=old_predicate.out.c > \"old_predicate.0.res.log\" 2> \"old_predicate.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "old_predicate.c"
  (alias old_predicate.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/old_predicate.out.c" "old_predicate.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "old_predicate.c"
  (alias old_predicate.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_old_predicate.c" "saida_harness_old_predicate.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "old_predicate.c"
  (alias "old_predicate.0.exec")
  (deps  "old_predicate.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    old_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=old_predicate.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "old_predicate.c"
  (alias "old_predicate.0.exec.show")
  (deps  "old_predicate.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    old_predicate.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=old_predicate.out.c > \"old_predicate.0.res.log\" 2> \"old_predicate.0.err.log\"'"))
)
(rule
  (alias "old_predicate.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/old_predicate.0.res.oracle" "old_predicate.0.res.log"))
)
(rule
  (alias "old_predicate.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/old_predicate.0.err.oracle" "old_predicate.0.err.log"))
)
(alias (name "old_predicate.diff")
  (deps (alias "old_predicate.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "old_predicate.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name disabled_runtest)
  (deps (alias disabled_runtest_config)))
(alias (name runtest)
  (deps (alias disabled_runtest)))
(alias (name runtest_config)
  (deps (alias disabled_runtest_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_runtest_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-saida.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/basic/runtest_config\n")
                 (echo "- \%{lib-available:frama-c-saida.core}: " %{lib-available:frama-c-saida.core} "\n")
  ))
)
