(copy_files ../*.*)
(alias (name runtest)
  (deps (alias runtest_config)))
; TEST FILE "nondet-init.c"
(alias (name "nondet-init.wtests")
  (deps (alias "nondet-init.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "nondet-init.c")
  (deps (alias "nondet-init.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/arrays/nondet-init.c
  (alias "nondet-init.0.exec.wtests")
  (targets "nondet-init.0.err.log" "nondet-init.0.res.log"  "nondet-init.out.c" "saida_harness_nondet-init.c" )
  (deps "nondet-init.0.exec.wtests" "../oracle/nondet-init.0.res.oracle" "../oracle/nondet-init.0.err.oracle"  "../oracle/nondet-init.out.c" "../oracle/saida_harness_nondet-init.c" "nondet-init.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "nondet-init.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    nondet-init.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nondet-init.out.c > \"nondet-init.0.res.log\" 2> \"nondet-init.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "nondet-init.c"
  (alias nondet-init.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nondet-init.out.c" "nondet-init.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "nondet-init.c"
  (alias nondet-init.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_nondet-init.c" "saida_harness_nondet-init.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "nondet-init.c"
  (alias "nondet-init.0.exec")
  (deps  "nondet-init.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    nondet-init.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nondet-init.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "nondet-init.c"
  (alias "nondet-init.0.exec.show")
  (deps  "nondet-init.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    nondet-init.c -lib-entry -main=func -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=nondet-init.out.c > \"nondet-init.0.res.log\" 2> \"nondet-init.0.err.log\"'"))
)
(rule
  (alias "nondet-init.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nondet-init.0.res.oracle" "nondet-init.0.res.log"))
)
(rule
  (alias "nondet-init.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/nondet-init.0.err.oracle" "nondet-init.0.err.log"))
)
(alias (name "nondet-init.diff")
  (deps (alias "nondet-init.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "nondet-init.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
; TEST FILE "array-of-struct.c"
(alias (name "array-of-struct.wtests")
  (deps (alias "array-of-struct.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "array-of-struct.c")
  (deps (alias "array-of-struct.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/arrays/array-of-struct.c
  (alias "array-of-struct.0.exec.wtests")
  (targets "array-of-struct.0.err.log" "array-of-struct.0.res.log"  "array-of-struct.out.c" "saida_harness_array-of-struct.c" )
  (deps "array-of-struct.0.exec.wtests" "../oracle/array-of-struct.0.res.oracle" "../oracle/array-of-struct.0.err.oracle"  "../oracle/array-of-struct.out.c" "../oracle/saida_harness_array-of-struct.c" "array-of-struct.c"  (package frama-c)  (package "frama-c-saida") )
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (run frama-c-wtests -brief "array-of-struct.0.exec.wtests" "frama-c -check -no-autoload-plugins -load-plugin=saida    array-of-struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=array-of-struct.out.c > \"array-of-struct.0.res.log\" 2> \"array-of-struct.0.err.log\"" ))
)
(rule ; COMPARE TARGET #0 OF TEST #0 FOR TEST FILE "array-of-struct.c"
  (alias array-of-struct.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/array-of-struct.out.c" "array-of-struct.out.c"))
)
(rule ; COMPARE TARGET #1 OF TEST #0 FOR TEST FILE "array-of-struct.c"
  (alias array-of-struct.0.exec.diff)
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/saida_harness_array-of-struct.c" "saida_harness_array-of-struct.c"))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "array-of-struct.c"
  (alias "array-of-struct.0.exec")
  (deps  "array-of-struct.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -load-plugin=saida    array-of-struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=array-of-struct.out.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "array-of-struct.c"
  (alias "array-of-struct.0.exec.show")
  (deps  "array-of-struct.c"  (package frama-c)  (package "frama-c-saida")  (universe))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -load-plugin=saida    array-of-struct.c -lib-entry -saida -saida-tricera-opts=\"-acsl\" -saida-keep-tmp -saida-out=array-of-struct.out.c > \"array-of-struct.0.res.log\" 2> \"array-of-struct.0.err.log\"'"))
)
(rule
  (alias "array-of-struct.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/array-of-struct.0.res.oracle" "array-of-struct.0.res.log"))
)
(rule
  (alias "array-of-struct.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
(action (diff "../oracle/array-of-struct.0.err.oracle" "array-of-struct.0.err.log"))
)
(alias (name "array-of-struct.diff")
  (deps (alias "array-of-struct.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name "runtest_config")
  (deps (alias "array-of-struct.diff"))
  (enabled_if (and true %{lib-available:frama-c-saida.core}))
)
(alias (name disabled_runtest)
  (deps (alias disabled_runtest_config)))
(alias (name runtest)
  (deps (alias disabled_runtest)))
(alias (name runtest_config)
  (deps (alias disabled_runtest_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_runtest_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-saida.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/arrays/runtest_config\n")
                 (echo "- \%{lib-available:frama-c-saida.core}: " %{lib-available:frama-c-saida.core} "\n")
  ))
)

