(rule (target "char_const.0.err.oracle") (mode fallback) (action (write-file "char_const.0.err.oracle" "")))
(rule (target "char_const.0.res.oracle") (mode fallback) (action (write-file "char_const.0.res.oracle" "")))
(rule (target "char_const.out.c") (mode fallback) (action (write-file "char_const.out.c" "")))
(rule (target "saida_harness_char_const.c") (mode fallback) (action (write-file "saida_harness_char_const.c" "")))
(rule (target "behavior.0.err.oracle") (mode fallback) (action (write-file "behavior.0.err.oracle" "")))
(rule (target "behavior.0.res.oracle") (mode fallback) (action (write-file "behavior.0.res.oracle" "")))
(rule (target "behavior.out.c") (mode fallback) (action (write-file "behavior.out.c" "")))
(rule (target "saida_harness_behavior.c") (mode fallback) (action (write-file "saida_harness_behavior.c" "")))
(rule (target "sum.0.err.oracle") (mode fallback) (action (write-file "sum.0.err.oracle" "")))
(rule (target "sum.0.res.oracle") (mode fallback) (action (write-file "sum.0.res.oracle" "")))
(rule (target "sum.parse.log") (mode fallback) (action (write-file "sum.parse.log" "")))
(rule (target "ternary_term.0.err.oracle") (mode fallback) (action (write-file "ternary_term.0.err.oracle" "")))
(rule (target "ternary_term.0.res.oracle") (mode fallback) (action (write-file "ternary_term.0.res.oracle" "")))
(rule (target "ternary_term.out.c") (mode fallback) (action (write-file "ternary_term.out.c" "")))
(rule (target "saida_harness_ternary_term.c") (mode fallback) (action (write-file "saida_harness_ternary_term.c" "")))
(rule (target "simple_ptr.0.err.oracle") (mode fallback) (action (write-file "simple_ptr.0.err.oracle" "")))
(rule (target "simple_ptr.0.res.oracle") (mode fallback) (action (write-file "simple_ptr.0.res.oracle" "")))
(rule (target "simple_ptr.out.c") (mode fallback) (action (write-file "simple_ptr.out.c" "")))
(rule (target "simple.0.err.oracle") (mode fallback) (action (write-file "simple.0.err.oracle" "")))
(rule (target "simple.0.res.oracle") (mode fallback) (action (write-file "simple.0.res.oracle" "")))
(rule (target "simple.out.c") (mode fallback) (action (write-file "simple.out.c" "")))
(rule (target "multiple_contracts.0.err.oracle") (mode fallback) (action (write-file "multiple_contracts.0.err.oracle" "")))
(rule (target "multiple_contracts.0.res.oracle") (mode fallback) (action (write-file "multiple_contracts.0.res.oracle" "")))
(rule (target "multiple_contracts.out.c") (mode fallback) (action (write-file "multiple_contracts.out.c" "")))
(rule (target "saida_harness_multiple_contracts.c") (mode fallback) (action (write-file "saida_harness_multiple_contracts.c" "")))
(rule (target "ternary_predicate.0.err.oracle") (mode fallback) (action (write-file "ternary_predicate.0.err.oracle" "")))
(rule (target "ternary_predicate.0.res.oracle") (mode fallback) (action (write-file "ternary_predicate.0.res.oracle" "")))
(rule (target "ternary_predicate.out.c") (mode fallback) (action (write-file "ternary_predicate.out.c" "")))
(rule (target "saida_harness_ternary_predicate.c") (mode fallback) (action (write-file "saida_harness_ternary_predicate.c" "")))
(rule (target "implies.0.err.oracle") (mode fallback) (action (write-file "implies.0.err.oracle" "")))
(rule (target "implies.0.res.oracle") (mode fallback) (action (write-file "implies.0.res.oracle" "")))
(rule (target "implies.out.c") (mode fallback) (action (write-file "implies.out.c" "")))
(rule (target "saida_harness_implies.c") (mode fallback) (action (write-file "saida_harness_implies.c" "")))
(rule (target "func_arguments.0.err.oracle") (mode fallback) (action (write-file "func_arguments.0.err.oracle" "")))
(rule (target "func_arguments.0.res.oracle") (mode fallback) (action (write-file "func_arguments.0.res.oracle" "")))
(rule (target "func_arguments.out.c") (mode fallback) (action (write-file "func_arguments.out.c" "")))
(rule (target "saida_harness_func_arguments.c") (mode fallback) (action (write-file "saida_harness_func_arguments.c" "")))
(rule (target "let2.0.err.oracle") (mode fallback) (action (write-file "let2.0.err.oracle" "")))
(rule (target "let2.0.res.oracle") (mode fallback) (action (write-file "let2.0.res.oracle" "")))
(rule (target "saida_harness_let2.c") (mode fallback) (action (write-file "saida_harness_let2.c" "")))
(rule (target "let.0.err.oracle") (mode fallback) (action (write-file "let.0.err.oracle" "")))
(rule (target "let.0.res.oracle") (mode fallback) (action (write-file "let.0.res.oracle" "")))
(rule (target "saida_harness_let.c") (mode fallback) (action (write-file "saida_harness_let.c" "")))
(rule (target "bool_const.0.err.oracle") (mode fallback) (action (write-file "bool_const.0.err.oracle" "")))
(rule (target "bool_const.0.res.oracle") (mode fallback) (action (write-file "bool_const.0.res.oracle" "")))
(rule (target "bool_const.out.c") (mode fallback) (action (write-file "bool_const.out.c" "")))
(rule (target "saida_harness_bool_const.c") (mode fallback) (action (write-file "saida_harness_bool_const.c" "")))
(rule (target "old_predicate.0.err.oracle") (mode fallback) (action (write-file "old_predicate.0.err.oracle" "")))
(rule (target "old_predicate.0.res.oracle") (mode fallback) (action (write-file "old_predicate.0.res.oracle" "")))
(rule (target "old_predicate.out.c") (mode fallback) (action (write-file "old_predicate.out.c" "")))
(rule (target "saida_harness_old_predicate.c") (mode fallback) (action (write-file "saida_harness_old_predicate.c" "")))
