name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        frama-c-image:
          - framac/frama-c:31.0

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.frama-c-image }}
      options: --user root

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - run: |
          opam install . --deps-only --with-test
          opam exec -- dune build
          opam exec -- dune runtest
