name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: |
          opam --cli=2.1 install . --deps-only --with-test
          opam --cli=2.1 exec -- frama-c-ptests
          opam --cli=2.1 exec -- dune build @install
          # Currently we can't run ptests because they depend on tricera,
          # which is not installed in the CI.
          # opam --cli=2.1 exec -- dune build @ptests
          opam --cli=2.1 exec -- dune runtest
