name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.13.1"
          - "5.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: |
          opam --cli=2.1 install . --deps-only --with-test
          frama-c-ptests
          opam --cli=2.1 exec -- dune build @install
          opam --cli=2.1 exec -- dune build @ptests
          opam --cli=2.1 exec -- dune runtest
